[project]
name = "capitulo-05"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-community>=0.3.27",
    "langchain-google-genai>=2.1.8",
    "langchain-tavily>=0.2.10",
    "python-dotenv>=1.1.1",
]
